name: "YAML to Github Output"
description: "Reads any key: value in a yaml file and sends it as a variable to the Github Output File"
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  file_path:
    description: "Path to the yaml file"
    required: true
  region:
    description: "AWS region (Optional)"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.file_path }}
    - ${{ inputs.region }}