name: Test YAML to GitHub Output Action

on:
  pull_request:
    branches: [master]
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Run YAML to Github Output Action without region filter
      id: yaml-output-global
      uses: ./
      with:
        file_path: "./.github/settings-simple-nested.yml"

    - name: Check global outputs and environment variables
      run: |
        if [[ "${{ env.APP_NAME }}" != "demo-app" ]]; then
          echo "Validation failed. Global 'APP_NAME' environment variable is not as expected."
          exit 1
        fi

    - name: Run YAML to Github Output Action with region filter
      id: yaml-output-region
      uses: ./
      with:
        file_path: "./.github/settings-simple-nested.yml"
        main_key: regions
        sub_key: us-west-1

    - name: Check regional outputs and environment variables
      run: |
        if [[ "${{ env.CLUSTER_NAME }}" != "us-cluster" ]]; then
          echo "Validation failed. 'CLUSTER_NAME' environment variable for us-west-1 is not as expected."
          exit 1
        fi